// <auto-generated />
using System;
using EventData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventData.Migrations
{
    [DbContext(typeof(EventDataContext))]
    [Migration("20210405073901_Init migration")]
    partial class Initmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventData.Models.ArchivedEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateArchived")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("ArchivedEvents");
                });

            modelBuilder.Entity("EventData.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateHappens")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxGuestsCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventData.Models.EventType", b =>
                {
                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("EventTypeVariantEventTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("EventTypeId");

                    b.HasIndex("EventTypeVariantEventTypeId");

                    b.ToTable("EventType");
                });

            modelBuilder.Entity("EventData.Models.EventTypeVariant", b =>
                {
                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventTypeVariants");

                    b.HasData(
                        new
                        {
                            EventTypeId = 0,
                            Name = "Conference"
                        },
                        new
                        {
                            EventTypeId = 1,
                            Name = "Seminar"
                        },
                        new
                        {
                            EventTypeId = 2,
                            Name = "Hackathon"
                        });
                });

            modelBuilder.Entity("EventData.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("EventGuest", b =>
                {
                    b.Property<int>("ListOfEventsId")
                        .HasColumnType("int");

                    b.Property<int>("ListOfGuestsId")
                        .HasColumnType("int");

                    b.HasKey("ListOfEventsId", "ListOfGuestsId");

                    b.HasIndex("ListOfGuestsId");

                    b.ToTable("EventGuest");
                });

            modelBuilder.Entity("EventData.Models.ArchivedEvent", b =>
                {
                    b.HasOne("EventData.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventData.Models.EventType", b =>
                {
                    b.HasOne("EventData.Models.EventTypeVariant", "EventTypeVariant")
                        .WithMany("EventTypes")
                        .HasForeignKey("EventTypeVariantEventTypeId");

                    b.Navigation("EventTypeVariant");
                });

            modelBuilder.Entity("EventGuest", b =>
                {
                    b.HasOne("EventData.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("ListOfEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventData.Models.Guest", null)
                        .WithMany()
                        .HasForeignKey("ListOfGuestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventData.Models.EventTypeVariant", b =>
                {
                    b.Navigation("EventTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
